ALTER TABLE issue
  ADD COLUMN creator_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN creator_avatar TEXT NOT NULL DEFAULT '',
  ADD COLUMN legacy_votes INTEGER NOT NULL DEFAULT 0;

ALTER TABLE comment
  ADD COLUMN legacy_id TEXT NOT NULL DEFAULT '';
